name: Publish

on:
  push:
    branches: [ master ]
    
jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['linux', 'windows', 'macOS']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64
    runs-on: ${{ matrix.os }}
    steps:    
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::v_$(date +"%Y.%m.%d_%H-%M")"
          
      - name: Build
        shell: bash
        run: |
          tag=${{ steps.tag.outputs.release_tag }}
          release_name="BumbleBee-$tag-${{ matrix.target }}"
          # Build everything
          dotnet publish src/Presentation/CommandLineInterface/CommandLineInterface.csproj --framework netcoreapp3.1 --runtime "${{ matrix.target }}" --self-contained true -c Release -o "$release_name"
          # Pack files
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            # Pack to zip for Windows
            7z a -tzip "${release_name}.zip" "./${release_name}/*"
          else
          tar czvf "${release_name}.tar.gz" "$release_name"
          fi
          # Delete output directory
          rm -r "$release_name"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: "BumbleBee*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
